// src/data/quests.ts
import type { Quest } from '@/types';

// This is the master list for Quests.
// This file is generated by the Admin Panel's CSV uploader.
// Do not edit this file directly.
export const QUESTS_DATA: Quest[] = [
  // This list will be populated by the admin's CSV upload.
  // For now, it remains empty.
];
