// src/data/quests.ts
import type { Quest } from '@/types';

// This is the master list for Quests.
// This file is generated by the Admin Panel's CSV uploader.
// Do not edit this file directly.
export const QUESTS_DATA: Quest[] = [
  {
    id: 'quest_0001',
    name: 'The Storehouse Secret',
    level: 2,
    adventurePackName: 'Free to Play',
    location: 'The Harbor',
    questGiver: 'Harbormaster Zin',
    normalExp: 228,
    hardExp: 246,
    eliteExp: 264,
    duration: 'Short',
    baseFavor: 3
  },
  {
    id: 'quest_0002',
    name: 'The Cannith Crystal',
    level: 2,
    adventurePackName: 'Free to Play',
    location: 'The Harbor',
    questGiver: 'Harbormaster Zin',
    normalExp: 336,
    hardExp: 363,
    eliteExp: 390,
    duration: 'Short',
    baseFavor: 3
  },
  {
    id: 'quest_0003',
    name: 'The Smuggler\'s Warehouse',
    level: 3,
    adventurePackName: 'Free to Play',
    location: 'The Harbor',
    questGiver: 'First Mate Fitzsimmons',
    normalExp: 432,
    hardExp: 468,
    eliteExp: 504,
    duration: 'Short',
    baseFavor: 6
  },
  {
    id: 'quest_0004',
    name: 'Walk the Butcher\'s Path',
    level: 3,
    adventurePackName: 'Free to Play',
    location: 'The Harbor',
    questGiver: 'Gable the Trapper',
    normalExp: 492,
    hardExp: 531,
    eliteExp: 570,
    duration: 'Medium',
    baseFavor: 6
  },
  {
    id: 'quest_0005',
    name: 'Kobold Assault',
    level: 2,
    adventurePackName: 'Free to Play',
    location: 'The Marketplace',
    questGiver: 'Crateos',
    normalExp: 366,
    hardExp: 396,
    eliteExp: 426,
    duration: 'Short',
    baseFavor: 3
  }
];
